# Generated by Django 3.1.4 on 2020-12-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='sixth_exercise',
        ),
    ]
