# Generated by Django 3.1.4 on 2020-12-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201211_1253'),
        ('app', '0005_progresspicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresspicture',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
    ]
