# Generated by Django 3.1.4 on 2021-09-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210322_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='notes',
        ),
    ]
