# Generated by Django 3.1.4 on 2021-09-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210928_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
    ]
